excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- TodoList/extensions

line_length:
warning: 200
error: 3000
ignores_comments: true
ignores_function_declarations: true

disabled_rules: # rule identifiers to exclude from running
- force_try
- force_cast
- trailing_whitespace


